platform : Add vndservicemanager  package to fix bootloop on yoshino devices
sonyxperiadev/device-sony-yoshino pull request #166
Opened 2020-12-29 16:46 UTC by ShujathMohd

https://github.com/sonyxperiadev/device-sony-common/blob/master/rootdir/vendor/etc/init/hw/init.common.rc#L44

init is failing to start vndservicemanager and throwing the below message :

Command 'start vndservicemanager' action=init (/system/etc/init/hw/init.rc:397) took 0ms and failed: service vndservicemanager not found
Command 'start vndservicemanager' action=init (/vendor/etc/init/hw/init.maple.rc:44) took 0ms and failed: service vndservicemanager not found

which is resulting in blank screen after the bootloader message until force shutdown.

This is fixed by adding vndservicemanager package.

Test case : Tested on maple and confirmed its booting.

2020-12-29 17:06 UTC, MarijnS95 requested changes
We should phase this out. `start vndservicemanager` exists solely to start the service early, but this service should not even be included on Android 11:

https://cs.android.com/android/platform/superproject/+/android-11.0.0_r3:build/make/target/product/base_vendor.mk;l=71-74

However, it implicitly ends up on my Griffin on Android 11:

```
griffin:/ # vndservice list
Found 3 services:
0	display.qservice: [android.display.IQService]
1	manager: [android.os.IServiceManager]
2	vendor.qcom.PeripheralManager: [vendor.qcom.IPeripheralManager]
```

Allow me to investigate why this happens, and whether we can (should!!) deprecate it and find a replacement for the vendor service (should afaik be moved over to hwservice).

2020-12-29 17:08 UTC, MarijnS95 commented
@ShujathMohd Can you try commenting out the `start` line instead, remove `vndservicemanager` from the build again (`make installclean`) and see if the device boots as well?

2020-12-29 17:09 UTC, ShujathMohd commented
> @ShujathMohd Can you try commenting out the `start` line instead, remove `vndservicemanager` from the build again (`make installclean`) and see if the device boots as well?

Aye aye captain, trying it now.

2020-12-29 18:09 UTC, ShujathMohd commented
@MarijnS95
#'ed out the start vndservicemanager in init.common.rc and make installclean.
still same issue, blank screen after the bootloader.

Logs still shows same message 


Command 'start vndservicemanager' action=init (/system/etc/init/hw/init.rc:397) took 0ms and failed: service vndservicemanager not found
Command 'start vndservicemanager' action=init (/vendor/etc/init/hw/init.maple.rc:44) took 0ms and failed: service vndservicemanager not found

Checked  into system/etc/init/hw/init.rc and found below lines 


    # Start essential services.
    start servicemanager
    start hwservicemanager
    start vndservicemanager

2020-12-31 07:11 UTC, sjllls commented
You need to set `PRODUCT_SHIPPING_API_LEVEL := 29` as well if you want to build `vndservicemanager` on A11.

2021-01-13 10:41 UTC, MarijnS95 commented
@ShujathMohd Interesting, AOSP removes `vndservicemanager` for API level >=30 but leaves the `start` in unconditionally; iirc these are not fatal though (it likely doesn't boot when something actually tries to use the service).

Anyway, I've just been pinged that we don't set the API level for Yoshino while we do (and have to) for all other platforms; expect a commit shortly that adds it as required. We will probably investigate deprecating and removing `vndservicemanager` at some later point in time.

2021-02-12 08:32 UTC, closed without merging

2021-02-12 08:32 UTC, jerpelea commented
fixed by adding PRODUCT_SHIPPING_API_LEVEL := 29

2021-02-12 08:34 UTC, MarijnS95 commented
No, we should set it to 26 like Poplar and Lilac, until we check all the boxes for a higher API level on the vendor side.

2021-02-12 08:34 UTC, MarijnS95 commented
be38467b6cfc0f4804cc7e7c09a3a1be9227d1b8 This was fixed here, btw.